function [posVelGUIData] = posVelGUI()
%trialVelGUI.m function to create trialVelGUI

screens = get(0,'MonitorPositions');
if size(screens,1) > 1
    scrn = screens(2,:);
else
    scrn = screens(1,:);
end

posVelGUIData.figHandle = figure('Name','Position and Velocity','NumberTitle','Off','MenuBar','none');

%create panel for subplots
posVelGUIData.plotPanel = uipanel('BackgroundColor',[0.7969 0.7969 0.7969],'Units','Normalized',...
    'Position',[0 0.05 1 0.95],'BorderType','none');

%create export button
posVelGUIData.indTrials = uicontrol('FontName','Arial','FontSize',15,...
    'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
    'Position',[.05 .01 .16 .03],'String','Individual Trials','Style','togglebutton',...
    'BackgroundColor',[0.7969 0.7969 0.7969],'Value',0);
posVelGUIData.fracTrialsLabel = uicontrol('FontName','Arial','FontSize',15,...
    'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
    'Position',[.235 .015 .1 .02],'String','Fraction','Style','text',...
    'BackgroundColor',[0.7969 0.7969 0.7969]);
posVelGUIData.fracTrials = uicontrol('FontName','Arial','FontSize',15,...
    'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
    'Position',[.35 .01 .04 .03],'String','1','Style','edit');
posVelGUIData.exportData = uicontrol('FontName','Arial','FontSize',15,...
    'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
    'Position',[.42 .01 .16 .03],'String','Export Data','Style','pushbutton',...
    'BackgroundColor',[0.7969 0.7969 0.7969]);
posVelGUIData.exportFig = uicontrol('FontName','Arial','FontSize',15,...
    'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
    'Position',[.605 .01 .16 .03],'String','Export Plot(s)','Style','pushbutton',...
    'BackgroundColor',[0.7969 0.7969 0.7969]);
posVelGUIData.printFig = uicontrol('FontName','Arial','FontSize',15,...
    'FontWeight','bold','ForegroundColor',[0 0 0],'Units','Normalized',...
    'Position',[.79 .01 .16 .03],'String','Print Plot(s)','Style','pushbutton',...
    'BackgroundColor',[0.7969 0.7969 0.7969]);

set(posVelGUIData.figHandle,'OuterPosition',[scrn(1)+0.5*(scrn(3)-scrn(1)) scrn(2) ...
    0.5*(scrn(3)-scrn(1)) scrn(4)]);
end